# Generated by Django 3.0.5 on 2022-04-10 14:06

import catalog.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenbergID', models.IntegerField(default=-1)),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('cover_url', models.URLField(default='no_cover')),
                ('small_cover_url', models.URLField(default='no_cover')),
                ('download_url', models.URLField(default='no_download')),
                ('centrality_rank', models.IntegerField(default=-1)),
                ('jaccard_calculated', models.BooleanField(default=False)),
                ('authors', djongo.models.fields.ArrayField(default=['No author'], model_container=catalog.models.Author)),
                ('bookshelves', djongo.models.fields.ArrayField(default=['No bookshelve'], model_container=catalog.models.BookShelve)),
                ('keywords', djongo.models.fields.ArrayField(default=['No keyword'], model_container=catalog.models.KeywordOccurrence)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('books', djongo.models.fields.ArrayField(model_container=catalog.models.BookOccurrence)),
            ],
        ),
    ]
